name: React-Application-CI-CD 

on:
  workflow_dispatch:
  push: 
    branches:
      main


jobs:
  compile:
    runs-on: Runner-1

    steps:
      - name: checkout step
        uses: actions/checkout@v4

      - name: gitleaks step
        uses: gitleaks/gitleaks-action@v2

      - name: gitleaks run
        run: | 
          gitleaks detect --no-git --exit-code 1 source ./frontend --report-path ./report/
          gitleaks detect --no-git --exit-code 1 source ./backend --report-path ./report/

      
  
